#!/usr/bin/python

"""
Go through the passed file (generated by gcc -fdump-tree-original-raw)
and get only the portion corresponding to the specified function.

get_function.py filename function
"""

import sys
import re

filename = sys.argv[1]
function = sys.argv[2]

f = open(filename, 'r')

in_function = False
for line in f:
  res = re.search(";; Function ([\S]+) ", line)
  if res:
    if res.group(1) == function:
      in_function = True
    else:
      in_function = False

  if in_function:
    print line,
    
f.close()
