% Produced by CVXGEN, 2015-10-08 17:09:32 -0400.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
xx = params.xx;
yy = params.yy;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable bb(5, 1);

  minimize(quad_form(xx*bb - yy, eye(10)));
cvx_end
vars.bb = bb;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
