PYTHON=/usr/bin/python
FILENAME=2048
DIRNAME=2048
FUNCNAME=main_loop

slice: preprocess
	$(PYTHON) inline.py $(DIRNAME)/$(FILENAME)3.c $(FUNCNAME) > $(DIRNAME)/$(FILENAME)_inline.c
	$(PYTHON) insert_loop_counts.py $(DIRNAME)/$(FILENAME)_inline.c > $(DIRNAME)/$(FILENAME)_loop_counts.c
	time $(PYTHON) slice.py $(DIRNAME)/$(FILENAME)_loop_counts.c loop_counter > $(DIRNAME)/$(FILENAME)_slice.c

td = echo "typedef int $1;" | cat - $(DIRNAME)/$(FILENAME)3.c > temp && mv temp $(DIRNAME)/$(FILENAME)3.c
preprocess:
	gcc -E $(DIRNAME)/$(FILENAME).c > $(DIRNAME)/$(FILENAME)2.c
	./cleanup_gccE.py $(DIRNAME)/$(FILENAME)2.c > $(DIRNAME)/$(FILENAME)3.c

	# Define custom types
	$(call td, "bool")
	$(call td, "uint8_t")
	$(call td, "uint32_t")
	$(call td, "size_t")

clean:
	rm -f $(DIRNAME)/$(FILENAME)2.c
	rm -f $(DIRNAME)/$(FILENAME)3.c
	rm -f $(DIRNAME)/$(FILENAME)_inline.c
	rm -f $(DIRNAME)/$(FILENAME)_loop_counts.c
	rm -f $(DIRNAME)/$(FILENAME)_slice.c
