PYTHON=/usr/bin/python
DIRNAME=2048
FILENAME=$(DIRNAME)/2048
FUNCNAME=main_loop
LOOP_COUNT_FLAGS=--write_to_file

slice: preprocess
	$(PYTHON) inline.py $(FILENAME)3.c $(FUNCNAME) > $(FILENAME)_inline.c
	$(PYTHON) insert_loop_counts.py $(FILENAME)_inline.c $(LOOP_COUNT_FLAGS) > $(FILENAME)_loop_counts.c
	time $(PYTHON) slice.py $(FILENAME)_loop_counts.c loop_counter > $(FILENAME)_slice.c
	$(PYTHON) globals.py $(FILENAME)_slice.c main_loop_slice true false > $(FILENAME)_slice_nofork.c

td = echo "typedef int $1;" | cat - $(FILENAME)3.c > temp && mv temp $(FILENAME)3.c
fd = echo "$1 ();" | cat - $(FILENAME)3.c > temp && mv temp $(FILENAME)3.c
gd = echo "$1;" | cat - $(FILENAME)3.c > temp && mv temp $(FILENAME)3.c
preprocess:
	gcc -E $(FILENAME).c > $(FILENAME)2.c
	./cleanup_gccE.py $(FILENAME)2.c > $(FILENAME)3.c

	$(call fd, "int strcmp")

	$(call td, "bool")
	$(call td, "uint8_t")
	$(call td, "uint32_t")
	$(call td, "size_t")

clean:
	rm -f $(FILENAME)2.c
	rm -f $(FILENAME)3.c
	rm -f $(FILENAME)_inline.c
	rm -f $(FILENAME)_loop_counts.c
	rm -f $(FILENAME)_slice.c
