PYTHON=/usr/bin/python
FILENAME=cleanup_empty_brace
DIRNAME=cleanup_empty_brace
FUNCNAME=main

slice: preprocess
	$(PYTHON) inline.py $(DIRNAME)/$(FILENAME)3.c $(FUNCNAME) > $(DIRNAME)/$(FILENAME)_inline.c
	$(PYTHON) insert_loop_counts.py $(DIRNAME)/$(FILENAME)_inline.c > $(DIRNAME)/$(FILENAME)_loop_counts.c
	$(PYTHON) slice.py $(DIRNAME)/$(FILENAME)_loop_counts.c loop_counter[1] > $(DIRNAME)/$(FILENAME)_slice_temp.c
	$(PYTHON) cleanup.py $(DIRNAME)/$(FILENAME)_slice_temp.c > $(DIRNAME)/$(FILENAME)_slice.c


td = echo "typedef int $1;" | cat - $(DIRNAME)/$(FILENAME)3.c > temp && mv temp $(DIRNAME)/$(FILENAME)3.c
preprocess:
	gcc -E $(DIRNAME)/$(FILENAME).c > $(DIRNAME)/$(FILENAME)2.c
	./cleanup_gccE.py $(DIRNAME)/$(FILENAME)2.c > $(DIRNAME)/$(FILENAME)3.c

	# Define custom types

clean:
	rm -f $(DIRNAME)/$(FILENAME)2.c
	rm -f $(DIRNAME)/$(FILENAME)3.c
	rm -f $(DIRNAME)/$(FILENAME)_inline.c
	rm -f $(DIRNAME)/$(FILENAME)_loop_counts.c
	rm -f $(DIRNAME)/$(FILENAME)_slice_temp.c
	rm -f $(DIRNAME)/$(FILENAME)_slice.c
